### Variables
@host = http://localhost:3000

### 1. Consulter toutes les équipes
GET {{host}}/teams

###

### 2. Consulter une équipe spécifique (ID 1)
### Vérifie si les Pokémons (Mew/Mewtwo du seed) sont bien inclus !
GET {{host}}/teams/1

###

### 3. Créer une nouvelle équipe
POST {{host}}/teams
Content-Type: application/json

{
    "name": "Team Rocket",
    "description": "Pour voler tous les Pokémons du monde",
    "user_id": "1"
}

###

### 4. Modifier une équipe (Changer le nom)
### Remplace l'ID par celui d'une équipe existante
PATCH {{host}}/teams/2
Content-Type: application/json

{
    "name": "Team Rocket Elite",
    "description": "La version améliorée"
}

###

### 5. Ajouter un Pokémon à une équipe
### Format : POST /teams/:teamId/pokemons/:pokemonId
### Ici on ajoute Salamèche (ID 4) à l'équipe 1
POST {{host}}/teams/5/pokemons/4

###

### 6. Retirer un Pokémon d'une équipe
### On retire Salamèche (ID 4) de l'équipe 1
DELETE {{host}}/teams/1/pokemons/4

###

### 7. Supprimer une équipe complète
DELETE {{host}}/teams/2